server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  profiles:
    default: local

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true

---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/our_home;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

---

spring:
  config:
    activate:
      on-profile: prod
    import: classpath:prod-db.yaml