spring:
  datasource:
    url: jdbc:mysql://localhost/jpa_board
    username: root
    password: rkdtmfrl903@
  jpa:
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true